#!/bin/bash

## #ddev-generated
## Description: Open PHPStorm with the current project
## Usage: macphpstorm
## Example: "ddev macphpstorm"

# Example is macOS-specific, but easy to adapt to any OS
open -a PHPStorm.app ${DDEV_APPROOT}

# AF's adaptation to Ubuntu
#phpstorm ${DDEV_APPROOT}
