networks:
  default:
    external: true
    name: ddev_default
services:
  db:
    build:
      args:
        BASE_IMAGE: drud/ddev-dbserver-mariadb-10.3:v1.15.1
        gid: '1000'
        uid: '1000'
        username: andrew
      context: /home/andrew/D9/d9custmoddevbook/.ddev/db-build
      dockerfile: /home/andrew/D9/d9custmoddevbook/.ddev/.dbimageBuild/Dockerfile
    command: ''
    container_name: ddev-d9custmoddevbook-db
    environment:
      COLUMNS: '189'
      DDEV_PROJECT: d9custmoddevbook
      LINES: '52'
      TZ: ''
    healthcheck:
      interval: 1s
      retries: 30
      start_period: 20s
      timeout: 2m
    hostname: d9custmoddevbook-db
    image: drud/ddev-dbserver-mariadb-10.3:v1.15.1-d9custmoddevbook-built
    labels:
      com.ddev.app-type: drupal9
      com.ddev.approot: /home/andrew/D9/d9custmoddevbook
      com.ddev.platform: ddev
      com.ddev.site-name: d9custmoddevbook
    ports:
    - 127.0.0.1:49153:3306/tcp
    restart: "no"
    stop_grace_period: 60s
    user: 1000:1000
    volumes:
    - source: mariadb-database
      target: /var/lib/mysql
      type: volume
      volume:
        nocopy: true
    - source: /home/andrew/D9/d9custmoddevbook/.ddev
      target: /mnt/ddev_config
      type: bind
    - ddev-global-cache:/mnt/ddev-global-cache:rw
  dba:
    container_name: ddev-d9custmoddevbook-dba
    environment:
      HTTPS_EXPOSE: 8037:8036
      HTTP_EXPOSE: 8036:8036
      PMA_PASSWORD: db
      PMA_USER: db
      TZ: ''
      UPLOAD_LIMIT: 1024M
      VIRTUAL_HOST: d9custmoddevbook.ddev.site
    healthcheck:
      interval: 2m
      retries: 1
      timeout: 2s
    hostname: d9custmoddevbook-dba
    image: phpmyadmin/phpmyadmin:5
    labels:
      com.ddev.app-type: drupal9
      com.ddev.approot: /home/andrew/D9/d9custmoddevbook
      com.ddev.platform: ddev
      com.ddev.site-name: d9custmoddevbook
    links:
    - db:db
    ports:
    - target: 80
    restart: "no"
  web:
    build:
      args:
        BASE_IMAGE: drud/ddev-webserver:v1.15.3
        gid: '1000'
        uid: '1000'
        username: andrew
      context: /home/andrew/D9/d9custmoddevbook/.ddev/web-build
      dockerfile: /home/andrew/D9/d9custmoddevbook/.ddev/.webimageBuild/Dockerfile
    cap_add:
    - SYS_PTRACE
    container_name: ddev-d9custmoddevbook-web
    environment:
      COLUMNS: '189'
      DDEV_PHP_VERSION: '7.3'
      DDEV_PRIMARY_URL: http://d9custmoddevbook.ddev.site:8000
      DDEV_PROJECT: d9custmoddevbook
      DDEV_PROJECT_TYPE: drupal9
      DDEV_ROUTER_HTTPS_PORT: '8443'
      DDEV_ROUTER_HTTP_PORT: '8000'
      DDEV_SITENAME: d9custmoddevbook
      DDEV_TLD: ddev.site
      DDEV_WEBSERVER_TYPE: nginx-fpm
      DDEV_XDEBUG_ENABLED: "false"
      DEPLOY_NAME: local
      DOCKER_IP: 127.0.0.1
      DOCROOT: web
      DRUSH_OPTIONS_URI: http://d9custmoddevbook.ddev.site:8000
      HOST_DOCKER_INTERNAL_IP: 172.17.0.1
      HTTPS_EXPOSE: 8443:80,8026:8025
      HTTP_EXPOSE: 8000:80,8025:8025
      IS_DDEV_PROJECT: "true"
      LINES: '52'
      SSH_AUTH_SOCK: /home/.ssh-agent/socket
      TZ: ''
      VIRTUAL_HOST: d9custmoddevbook.ddev.site
    external_links:
    - ddev-router:d9custmoddevbook.ddev.site
    extra_hosts:
    - host.docker.internal:172.17.0.1
    healthcheck:
      interval: 1s
      retries: 20
      start_period: 20s
      timeout: 2m
    hostname: d9custmoddevbook-web
    image: drud/ddev-webserver:v1.15.3-d9custmoddevbook-built
    labels:
      com.ddev.app-type: drupal9
      com.ddev.approot: /home/andrew/D9/d9custmoddevbook
      com.ddev.platform: ddev
      com.ddev.site-name: d9custmoddevbook
    links:
    - db:db
    ports:
    - 127.0.0.1::80/tcp
    - 127.0.0.1::443/tcp
    restart: "no"
    user: 1000:1000
    volumes:
    - consistency: cached
      source: /home/andrew/D9/d9custmoddevbook
      target: /var/www/html
      type: bind
    - /home/andrew/D9/d9custmoddevbook/.ddev:/mnt/ddev_config:ro
    - /home/andrew/D9/d9custmoddevbook/.ddev/nginx_full:/etc/nginx/sites-enabled:ro
    - /home/andrew/D9/d9custmoddevbook/.ddev/apache:/etc/apache2/sites-enabled:ro
    - ddev-global-cache:/mnt/ddev-global-cache:rw
    - ddev-ssh-agent_socket_dir:/home/.ssh-agent:rw
version: '3.6'
volumes:
  ddev-global-cache:
    name: ddev-global-cache
  ddev-ssh-agent_socket_dir:
    external: true
    name: ddev-ssh-agent_socket_dir
  mariadb-database:
    name: d9custmoddevbook-mariadb

